kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "jenkins-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/orhanIBM/jenkins-demo"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: ./Jenkinsfile