kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "jenkins-pipeline"
spec:
  source:
    git:
      uri: "githublink here"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: some/repo/dir/filename 